import turtle

turtle.title("My Initials")
turtle.bgcolor("blue")
turtle.shape("classic")
turtle.setup(500,500)
turtle.shape("turtle")
screen = turtle.Screen()
Taco = turtle.Turtle()
turtle.setx(-120)
turtle.sety(0)

turtle.forward(100)
turtle.right(180)
turtle.forward(50)
turtle.left(90)
turtle.forward(90)
turtle.penup()
turtle.left(135)
turtle.forward(120)
turtle.right(135)
turtle.pendown()
turtle.forward(90)
turtle.left(90)
turtle.forward(100)
turtle.left(90)
turtle.forward(50)
turtle.left(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)
turtle.right(90)
turtle.forward(100)
turtle.right(90)
turtle.forward(50)